'\" t
.\"     Title: pcp_proc_info
.\"    Author: The Pgpool Global Development Group
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 2018
.\"    Manual: Pgpool-II 4.0.3 文書
.\"    Source: Pgpool-II 4.0.3
.\"  Language: Japanese
.\"
.TH "PCP_PROC_INFO" "1" "2018" "Pgpool-II 4.0.3" "Pgpool-II 4.0.3 文書"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "名前"
pcp_proc_info \- Pgpool\-II の子プロセス情報を表示する
.SH "概要"
.HP \w'\fBpcp_proc_info\fR\ 'u
\fBpcp_proc_info\fR [\fIoptions\fR...] [\fIprocessid\fR]
.SH "説明"
.PP
\fBpcp_proc_info\fR
は
Pgpool\-II
の子プロセス情報を表示します。
.SH "オプション"
.PP
.PP
\fB\-a\fR
.br
\fB\-\-all\fR
.RS 4
すべての子プロセスと、それに関するコネクションスロットを表示します。
.RE
.PP
\fB\-P \fR\fB\fIPID\fR\fR
.br
\fB\-\-process\-id=\fR\fB\fIPID\fR\fR
.RS 4
Pgpool\-II 子プロセスの PID を指定します。
.RE
.PP
\fBその他\fR
.RS 4
\fBpcp_common_options\fR(1)
を参照してください。
.RE
もし\-aオプションも\-Pオプションも指定されない場合は、すべての接続されたPgpool\-II子プロセスが表示されます。 この場合、接続された子プロセスが存在しない場合は、"No process information available"メッセージだけが表示されます。
.SH "例"
.PP
例を示します。
.sp
.if n \{\
.RS 4
.\}
.nf
$ pcp_proc_info \-p 11001 1406
test t\-ishii 2018\-07\-09 16:43:53 2018\-07\-09 16:44:08 3 0 1 1435 1 1406 0
test t\-ishii 2018\-07\-09 16:43:53 2018\-07\-09 16:44:08 3 0 1 1436 1 1406 1
    
.fi
.if n \{\
.RE
.\}
.PP
結果は以下の順のとおりです。
.sp
.if n \{\
.RS 4
.\}
.nf
1\&. 接続先のデータベース名
2\&. 接続先のユーザ名
3\&. Pgpool\-IIプロセスの起動時刻
4\&. バックエンドへの接続時刻
5\&. プロトコルのメジャーバージョン
6\&. プロトコルのマイナーバージョン
7\&. 接続の再利用カウンタ値
8\&. PostgreSQLバックエンドプロセスのプロセスID
9\&. フロントエンドが接続中なら1、そうでなければ0
10\&. pgpool子プロセスID
11\&. PostgreSQLバックエンドID
.fi
.if n \{\
.RE
.\}
.PP
コネクションがバックエンドに対して張られていない場合、データは表示されません。 コネクション情報が複数ある場合、複数行に 1 行 1 コネクション情報で表示されます。
.PP
\fB\-\-verbose\fR
オプションは出力内容を理解するのに役に立ちます。例：
.sp
.if n \{\
.RS 4
.\}
.nf
$ pcp_proc_info \-p 11001 \-\-verbose 1406
Database     : test
Username     : t\-ishii
Start time   : 2018\-07\-09 16:43:53
Creation time: 2018\-07\-09 16:44:08
Major        : 3
Minor        : 0
Counter      : 1
Backend PID  : 1435
Connected    : 1
PID          : 1406
Backend ID   : 0
Database     : test
Username     : t\-ishii
Start time   : 2018\-07\-09 16:43:53
Creation time: 2018\-07\-09 16:44:08
Major        : 3
Minor        : 0
Counter      : 1
Backend PID  : 1436
Connected    : 1
PID          : 1406
Backend ID   : 1
    
.fi
.if n \{\
.RE
.\}
