'\" t
.\"     Title: pcp_proc_info
.\"    Author: The Pgpool Global Development Group
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 2018
.\"    Manual: pgpool-II 4.0.3 Documentation
.\"    Source: pgpool-II 4.0.3
.\"  Language: English
.\"
.TH "PCP_PROC_INFO" "1" "2018" "pgpool-II 4.0.3" "pgpool-II 4.0.3 Documentation"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pcp_proc_info \- displays the information on the given Pgpool\-II child process ID
.SH "SYNOPSIS"
.HP \w'\fBpcp_proc_info\fR\ 'u
\fBpcp_proc_info\fR [\fIoptions\fR...] [\fIpgpool_child_processid\fR]
.SH "DESCRIPTION"
.PP
\fBpcp_proc_info\fR
displays the information on the given Pgpool\-II child process ID\&.
.SH "OPTIONS"
.PP
.PP
\fB\-a\fR
.br
\fB\-\-all\fR
.RS 4
Display all child processes and their available connection slots\&.
.RE
.PP
\fB\-P \fR\fB\fIPID\fR\fR
.br
\fB\-\-process\-id=\fR\fB\fIPID\fR\fR
.RS 4
PID of
Pgpool\-II
child process\&.
.RE
.PP
\fBOther options \fR
.RS 4
See
\fBpcp_common_options\fR(1)\&.
.RE
If \-a nor \-P is not specified, process information of all connected
Pgpool\-II
child process will be printed\&. In this case if there\*(Aqs no connected
Pgpool\-II
child process, nothing but "No process information available" message will be printed\&.
.SH "EXAMPLE"
.PP
Here is an example output:
.sp
.if n \{\
.RS 4
.\}
.nf
$ pcp_proc_info \-p 11001 1406
test t\-ishii 2018\-07\-09 16:43:53 2018\-07\-09 16:44:08 3 0 1 1435 1 1406 0
test t\-ishii 2018\-07\-09 16:43:53 2018\-07\-09 16:44:08 3 0 1 1436 1 1406 1
    
.fi
.if n \{\
.RE
.\}
.PP
The result is in the following order:
.sp
.if n \{\
.RS 4
.\}
.nf
1\&. connected database name
2\&. connected user name
3\&. process start\-up timestamp
4\&. connection created timestamp
5\&. protocol major version
6\&. protocol minor version
7\&. connection\-reuse counter
8\&. PostgreSQL backend process id
9\&. 1 if frontend conncted 0 if not
10\&. pgpool child process id
11\&. PostgreSQL backend id 
.fi
.if n \{\
.RE
.\}
.PP
If there is no connection to the backends, nothing will be displayed\&. If there are multiple connections, one connection\*(Aqs information will be displayed on each line multiple times\&.
.PP
The
\fB\-\-verbose\fR
option can help understand the output\&. For example:
.sp
.if n \{\
.RS 4
.\}
.nf
$ pcp_proc_info \-p 11001 \-\-verbose 1406
Database     : test
Username     : t\-ishii
Start time   : 2018\-07\-09 16:43:53
Creation time: 2018\-07\-09 16:44:08
Major        : 3
Minor        : 0
Counter      : 1
Backend PID  : 1435
Connected    : 1
PID          : 1406
Backend ID   : 0
Database     : test
Username     : t\-ishii
Start time   : 2018\-07\-09 16:43:53
Creation time: 2018\-07\-09 16:44:08
Major        : 3
Minor        : 0
Counter      : 1
Backend PID  : 1436
Connected    : 1
PID          : 1406
Backend ID   : 1
    
.fi
.if n \{\
.RE
.\}
